### PR TITLE
Add types

### PR DESCRIPTION
**Pull request by nfroidure**

### CODE REVIEW

**Comment by SebastienElet** [comment]
Did you use a codemod ?

**Comment by nfroidure** [comment]
@SebastienElet no idea how codemod could have been used here, I had lots of pain determining types but now, it is behind me :dancing_men: .

I'm curious to see how we will take advantage of this addition for our back-end. It already helped to fix some problems in the current code base to add types.

**Comment by SebastienElet** [comment]
@nfroidure I wonder also how to use codemod to convert existing javascript codebase, but it seems airbnb is using it. I invite you to watch this conf about the typescript migration of airbnb : https://www.youtube.com/watch?v=P-J9Eg7hJwE

I did not spotted yet on my backend but I choose to migrate file by file instead of migrating the whole codebase :/

Btw, you did a nice work and even if it's almost impossible to review I will take a look because I think I may learn some tricks ;-)

**Comment by nfroidure** [comment]
Tbh, instead of reviewing, I would prefer if you can run `npm init @whook` and tell me what you think about the dev experience and what could be improved before the next major version.

**Pull request merged**
