### PR TITLE
refactor(@whook/graphql): update Apollo server to the last major version

### LINKED ISSUE #140: `apollographql/apollo-server` breaks the build
The build is broken since TypeScript 4.8:
```
> @whook/graphql@10.0.3 build
> rimraf -f 'dist' && tsc --outDir dist

Error: ../../node_modules/apollo-server-core/dist/types.d.ts(3,50): error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@graphql-tools/schema")' call instead.
lerna ERR! npm run build exited 2 in '@whook/graphql'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
Error: Process completed with exit code 2.
```
Full logs: https://github.com/nfroidure/whook/runs/8152053130?check_suite_focus=true

Temporary adding:
```diff
import type { IMocks } from '@graphql-tools/mock';
+ // @ts-ignore
import type { IExecutableSchemaDefinition } from '@graphql-tools/schema';

```

Fixes the build, issue reported here: https://github.com/apollographql/apollo-server/issues/6868#issuecomment-1233786862

### PR DESCRIPTION
**Pull request by nfroidure**
fix #140

### CODE REVIEW

**Review by Oupsla — APPROVED** [review]
LGTM
Any breaking change for users ? (Maybe the context injected ?)

**Comment by nfroidure** [comment]
@Oupsla yes, the main issue is with the context. In the previous version, the server were asking for a context function. In the new version, it is required at the http transaction level : https://github.com/nfroidure/whook/pull/143/files#diff-1eb63035ea7297ec70ff6178114f5f2b92254e9f3dad38f597be116d2c8080acR118-R122

I was wondering if I should change the newly create `GRAPHQL_SERVER_CONTEXT` service into a function to cover wider usages, WDYT? Do you use it currently?
https://github.com/nfroidure/whook/pull/143/files#diff-1eb63035ea7297ec70ff6178114f5f2b92254e9f3dad38f597be116d2c8080acR84

**Comment by Oupsla** [comment]
> I was wondering if I should change the newly create `GRAPHQL_SERVER_CONTEXT` service into a function to cover wider usages, WDYT? 

Maybe to stay compatible with the previous context function it could be nice.
At the moment, I only use the context do clear graphQL loaders between each calls


```ts 

async function initGraphQLServerConfig({
  graphQLLoaders,
}: {
  graphQLLoaders: GraphQLLoadersService;
}) {
  (...)

  return {
    context: async (context) => {
      await graphQLLoaders.clearAllLoaders();
      return context;
    },
   (...)
  };
}

**Comment by nfroidure** [comment]
@Oupsla ok, I'll fix this before merging. Thanks for your feedback

**Pull request merged**
